# Generated by Django 5.1.5 on 2025-01-30 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_app", "0003_task_description_task_due_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
